### PR TITLE
funcr: Handle nil Stringer, Marshaler, error

### LINKED ISSUE #125: funcr: handle fmt.Stringer that panics on nil
I ran into this with klog in Kubernetes (see https://github.com/kubernetes/klog/issues/278). While I haven't tested it, funcr is probably also affected, at least here but potentially also elsewhere:
https://github.com/go-logr/logr/blob/99e02a994f50f904b6b201df394776cf687238a9/funcr/funcr.go#L360

The problem is that log calls might pass a nil pointer for a struct which implements `fmt.Stringer`, but then segfaults when called. Here's an example:
https://github.com/kubernetes/kubernetes/blob/a1e8a5bf39d48719dfbcf49ea09223ee04840502/pkg/kubelet/kubelet.go#L2334-L2335

I think it is reasonable to expect that a logging implementation is resilient against such problems. That means that funcr must either check for nil beforehand or deal with the panic. I'm undecided. Perhaps `fmt.Sprintf("%q", <nil stringer>)` can serve as reference.

### PR DESCRIPTION
**Pull request by thockin**
Produce a useful error rather than panic.

Fixes #125

### CODE REVIEW

File: funcr/funcr.go [hunk 1]
```diff
@@ -341,6 +341,17 @@ const (
 	flagRawStruct = 0x1 // do not print braces on structs
 )
 
+func isNil(i interface{}) bool {
```
Comment (pohly) [inline funcr/funcr.go:344]: Is this faster than wrapping the MarshalLog and String invocations in a function which recovers from a failure inside the called function?

That's how Dims solved it in klog:
https://github.com/kubernetes/klog/commit/125dec9bbe623ab72ec25154974434e2ffc28782#diff-d11e021bcd662e6127823cd93eeac7a9aec303039137c2f27974cff399142e84

It has two advantages:
- if the interface contains a valid pointer to a struct but the called function then crashes for some other reason (nil access for a field in that struct, for example), then the recovery mechanism catches that, too
- if the function implementation itself handles nil gracefully, then logging keeps using that fallback instead of making up its own

**Comment by thockin** [comment]
It has a distinct disadvantage, too - if the user code panics for ANY
REASON, we'll just eat it and continue.   Bad.

The point about valid implementation is apt.  Looking at how printf does
it, I guess that is the better answer..

**Comment by thockin** [comment]
Retooled - PTAL

**Comment by pohly** [comment]
> It has a distinct disadvantage, too - if the user code panics for ANY REASON, we'll just eat it and continue. Bad.

We could log the panic as an error - that might raise awareness that the code is not as robust as it needs to be.

Hiding the problem where it won't be noticed isn't good, but I think it's still better than aborting the program. Log calls are often not as well tested as the rest of the code. Suppose someone bumps up the log level to debug some problem and then the program aborts somewhere else entirely because of a nil pointer exception - they might not be able to fix the problem and are stuck.


> The point about valid implementation is apt. Looking at how printf does it, I guess that is the better answer..

It dumps the panic: https://go.dev/play/p/KC2odl1qSZf

File: funcr/funcr.go [hunk 2]
```diff
@@ -596,6 +596,56 @@ func isEmpty(v reflect.Value) bool {
 	return false
 }
 
+func invokeMarshaler(m logr.Marshaler) (ret interface{}) {
+	defer func() {
+		if err := recover(); err != nil {
+			if isNil(m) {
+				ret = "<nil-logr-marshaler>"
+			} else {
+				panic(err)
```
Comment (pohly) [inline funcr/funcr.go:605]: I think this should return a string explaining the problem, similar to what fmt.Sprint does.

We could also log an error, to raise awareness.

**Comment by thockin** [comment]
I don't know.  I sort of feel like, if the user called `panic()` and we
swallow their panic, we're doing something wrong.  I mean, really this is a
very corner-case of a corner-case, but I thought passing the panic() on was
less surprising.

https://go.dev/play/p/NGMzpwFf90I

That's just weird to me

**Comment by pohly** [comment]
Tim Hockin ***@***.***> writes:
> I don't know.  I sort of feel like, if the user called `panic()` and we
> swallow their panic, we're doing something wrong.

I guess the more common case will be that user didn't explicitly call
panic, but rather forgot a nil for a field or a bounds check. We may be
able to tell the difference from looking at the error from recover, but
I am not sure whether we should bother.

**Comment by thockin** [comment]
Alt model pushed as a new commit, but I am still unsure what is "right".

DO NOT MERGE YET PLEASE :)

**Comment by thockin** [comment]
I put up a Twitter poll and  it was almost evenly split between "let the panic happen" and "catch panics and print", with "let them happen" taking a single-digit percentage lead.

Thoughts?

**Comment by pohly** [comment]
I prefer to emulate the behavior of fmt.

Besides being consistent (why should `fmt.Printf` continue and `logger.Info` not?) it also makes a bit more sense to me (see argument above about not making the situation worse when a program is already misbehaving).

**Comment by thockin** [comment]
OK, I retooled to be similar to fmt.  Added it to benchmark, but nothing to report.

PTAL

**Review by pohly — APPROVED** [review]
