### PR TITLE
funcr: Handle nested empty groups properly

### LINKED ISSUE #273: funcr: slog output omits intermediate groups
I'm working on implementing a SlogSink for another logger and looked to funcr for guidance on how to handle certain cases with groups but found that it behaves unexpectedly.

I added the following lines to `ExampleToSlogHandler`:

```go
slogLogger.WithGroup("a").Info("single empty group")
slogLogger.WithGroup("a").WithGroup("b").Info("chained empty groups")
slogLogger.WithGroup("a").WithGroup("b").With("str", "abc").Info("first group empty")
slogLogger.WithGroup("a").With("str", "abc").WithGroup("b").Info("last group empty")
slogLogger.WithGroup("a").With("str", "abc").WithGroup("b").WithGroup("c").With("x", 1).Info("middle group empty")
```

The output I got was:

```
"level"=0 "msg"="single empty group"
"level"=0 "msg"="chained empty groups"}
"level"=0 "msg"="first group empty" "b"={"str"="abc"}}
"level"=0 "msg"="last group empty" "a"={"str"="abc"}
"level"=0 "msg"="middle group empty" "a"={"str"="abc" "c"={"x"=1}}}
```

Apart from the trailing curly brackets I expected funcr to behave like a `slog.TextHandler`, so something like:

```
"level"=0 "msg"="single empty group"
"level"=0 "msg"="chained empty groups"
"level"=0 "msg"="first group empty" "a"={"b"={"str"="abc"}}
"level"=0 "msg"="last group empty" "a"={"str"="abc"}
"level"=0 "msg"="middle group empty" "a"={"str"="abc" "b"={"c"={"x"=1}}}
```

I'm assuming the omission of the intermediate group is causing the trailing `}` problem.

### PR DESCRIPTION
**Pull request by thockin**
This ruins the whole idea of pre-rendering.  We simply don't know if we have to render a group until we know the whole log record.  Not having values at the time that `WithGroup` is called is not sufficient information.

Fixes #273

### CODE REVIEW

File: slogr_test.go [hunk 1]
```diff
@@ -127,6 +127,7 @@ func TestRunSlogTestsOnSlogHandlerLogSink(t *testing.T) {
 		"a Handler should handle the WithGroup method",
 		"a Handler should handle multiple WithGroup and WithAttr calls",
 		"a Handler should not output groups for an empty Record",
+		"a Handler should not output groups if there are no attributes",
```
Comment (pohly) [inline slogr_test.go:130]: There might be a way to run the Slog tests as sub-tests now,  https://github.com/golang/go/issues/61758 got resolved. This might be a way to simplify this testing. Not important right now, just a thought.

**Review by pohly — APPROVED** [review]
I don't follow all of the implementation, but the test cases look thorough, so LGTM from me.
